apiVersion: v1
kind: Pod
metadata:
  name: pod-with-http-liveness-probe
spec:
  containers:
  - image: shuanger/kubia-unhealthy
    name: kubia
    livenessProbe:
      httpGet:
        path: /
        port: 8080
      initialDelaySeconds: 15
