apiVersion: v1
kind: Service
metadata:
  name: k8s-hello-svc
spec:
  ports:
  - name: http
    port: 80
    targetPort: http
  - name: https
    port: 443
    targetPort: https 
  selector:
    app: hello-world
