apiVersion: v1
kind: Pod
metadata:
  name: app-six
  labels:
    FrontEnd: Angular
    Language: TypeScript
    Webpack: V5.0.3
spec:
  containers:
  - name: kubia
    image: shuanger/kubia
    ports:
    - containerPort: 8080

